# Generated by Django 4.1.1 on 2022-09-14 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("ef0308d9-487d-400d-9eba-eff7b205c2b4"),
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("ef0308d9-487d-400d-9eba-eff7b205c2b4"),
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("description", models.TextField(blank=True, null=True)),
                ("pic", models.ImageField(blank=True, null=True, upload_to="media/")),
                ("pic1", models.ImageField(blank=True, null=True, upload_to="media/")),
                ("pic2", models.ImageField(blank=True, null=True, upload_to="media/")),
                ("discount_price", models.FloatField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        choices=[("P", "primary"), ("S", "secondary"), ("D", "danger")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="products", to="products.category"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
