version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: python3 manage.py runserver
    # gunicorn mmgrupp_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - .:/app

    expose:
      - 8000
    # env_file:
    #   - ./.env
    environment:
      - ENVIROMENT=development
  nginx:
    build: 
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "1338:80"
    depends_on:
      - web
    restart: always

    
volumes:
  static_volume:
  redisdata: