# Generated by Django 4.1.1 on 2022-09-13 16:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_address_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('409fce67-2c6e-4046-844d-eabfdc771d8f'), editable=False, unique=True),
        ),
    ]
