# Generated by Django 4.1.1 on 2022-09-14 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("ef0308d9-487d-400d-9eba-eff7b205c2b4"),
                editable=False,
                unique=True,
            ),
        ),
    ]
